<a href="https://colab.research.google.com/github/kennedy-harris/mis433/blob/main/Python%20Basics%20Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [90]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Kennedy
Welcome, Kennedy!


In [91]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')

print(f)

f = float(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 140
140
140.0F is 60.0 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [92]:
# complete your program here
c = input('Please enter the temperature in Celcius: ')

print (c)

c = float(c)

f = (c * 9/5) + 32

print(f'{c}C is {f} in Fahrenheit. ')

Please enter the temperature in Celcius: 60
60
60.0C is 140.0 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [94]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')

if m == 'C':
  d = float(d)
  t = (d * 9/5) + 32
  print(f'{d}C is {t} in Fahrenheit')
elif m == 'F':
  d = float(d)
  t = (d - 32) * 5/9
  print(f'{d}F is {t} in Celsius')

Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60.0C is 140.0 in Fahrenheit


## Question 2

Have some fun with strings.

In [95]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [96]:
# Find the length of this sentence.
len(sentence)

48

In [97]:
# Convert the whole string to lower case.
sentence.lower()

'talk is cheap. show me the code - linus torvalds'

In [98]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[9:-9])

heap. Show me the code - Linus


In [99]:
# Split the sentence into a list of substrings by space ' '.
print(sentence.split(' '))

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [100]:
# Given the sentence, output a list of words in lowercase (without punctuations).
print(sentence.lower().replace('.', '').replace('-','').split())

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [101]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
count = 0
for v in vowels:
    print(v, sentence.lower().count(v))
    count += sentence.lower().count(v)
print(f"The total number of vowels is {count}.")

a 3
e 4
i 2
o 3
u 1
The total number of vowels is 13.


In [102]:
# Find the positions (indexes) of all vowels in the sentence.
vowels = 'aeiou'

for i in range(len(sentence)):
  if sentence[i].lower() in vowels:
    print(i)

1
5
10
11
17
21
25
28
30
35
37
41
44


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [103]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
  cubes.append(i**3)
print(cubes)

[0, 1, 8, 27, 64]


In [104]:
# Use list comprehension to create the same list
cubes_new = [i**3 for i in range(5)]
print(cubes_new)

[0, 1, 8, 27, 64]


In [105]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
sv = [i for i in range(len(sentence)) if sentence[i].lower() in 'aeiou']
print(sv)

[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [106]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')
n = int(n)

# add your code here
if n == 1:
  fibonacci = [0]
elif n == 2:
  fibonacci = [0, 1]
elif n > 2:
  fibonacci = [0, 1]
  while len(fibonacci) < n:
    fibonacci.append(fibonacci[-1] + fibonacci[-2])

print(fibonacci)

How many numbers do you want? 20
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [107]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {'Pfizer':0.95, 'Moderna':0.95, 'AstraZeneca':0.72, 'Johnson & Johnson':0.66}

In [108]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
e = v_dict[v]
print(f'The efficacy of {v} is {e}.')

Which vaccine? Pfizer
The efficacy of Pfizer is 0.95.


In [109]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914
v_dict

{'Pfizer': 0.95,
 'Moderna': 0.95,
 'AstraZeneca': 0.72,
 'Johnson & Johnson': 0.66,
 'Sputnik V': 0.914}

In [110]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = 0.5038
v_dict

{'Pfizer': 0.95,
 'Moderna': 0.95,
 'AstraZeneca': 0.72,
 'Johnson & Johnson': 0.66,
 'Sputnik V': 0.914,
 'Sinovac': 0.5038}

In [111]:
# Print vaccines with efficacy lower than 90%.
for v in v_dict:
  if v_dict[v] < 0.9:
    print(v, v_dict[v])

AstraZeneca 0.72
Johnson & Johnson 0.66
Sinovac 0.5038


In [112]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']
v_dict

{'Pfizer': 0.95,
 'Moderna': 0.95,
 'AstraZeneca': 0.72,
 'Johnson & Johnson': 0.66,
 'Sputnik V': 0.914}

In [113]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

alphabet = 'abcdefghijklmnopqrstuvwxyz'

ch_dict = {}

# Use a loop to iterate all characters
# add your code here
for ch in alphabet:
  ch_dict[ch] = sentence.count(ch)
# print the dictionary
print(ch_dict)

{'a': 1, 'b': 1, 'c': 1, 'd': 1, 'e': 3, 'f': 1, 'g': 1, 'h': 2, 'i': 1, 'j': 1, 'k': 1, 'l': 1, 'm': 1, 'n': 1, 'o': 4, 'p': 1, 'q': 1, 'r': 2, 's': 1, 't': 2, 'u': 2, 'v': 1, 'w': 1, 'x': 1, 'y': 1, 'z': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [ ]:
import numpy as np

In [114]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.arange(2, 42, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [115]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.arange(1, 41, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [116]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.array([np.arange(i*10, i*10+10) for i in range(10)])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
M.shape

(10, 10)

In [118]:
# Count the numbers in M with an absolute value greater than 1.
np.sum(np.abs(M) > 1)

np.int64(25)

In [119]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of columns (input another integer >= 3)
c = input('column count: ')

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, (int(r), int(c)))
arr

Row count: 7
column count: 4


array([[17, 10, 18, 10],
       [16, 17, 18, 19],
       [11, 16, 11, 13],
       [10, 18, 12, 11],
       [13, 13, 19, 10],
       [10, 18, 17, 18],
       [11, 10, 16, 14]])

In [120]:
# output the element in the first row and the third column
arr[0, 2]

np.int64(18)

In [121]:
# output the element in the second row and the last column
arr[1, -1]

np.int64(19)

In [122]:
# output the second row of the array
arr[1,]

array([16, 17, 18, 19])

In [123]:
# output the second last row of the array
arr[-2,]

array([10, 18, 17, 18])

In [124]:
# output the second column of the array
arr[:, 1]

array([10, 17, 16, 18, 13, 18, 10])

In [125]:
# output the second last column of the array
arr[:, -2]

array([18, 18, 11, 12, 19, 17, 16])

In [126]:
# output the upper-left 3x3 sub-array
arr[:3, :3]

array([[17, 10, 18],
       [16, 17, 18],
       [11, 16, 11]])

In [127]:
# output the bottom-left 3x3 sub-array
arr[-3:, :3]

array([[13, 13, 19],
       [10, 18, 17],
       [11, 10, 16]])

In [128]:
# output the upper-right 3x3 sub-array
arr[:3, -3:]

array([[10, 18, 10],
       [17, 18, 19],
       [16, 11, 13]])

In [129]:
# output the bottom-right 3x3 sub-array
arr[-3:, -3:]

array([[13, 19, 10],
       [18, 17, 18],
       [10, 16, 14]])

In [130]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1, 51)
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A = A.reshape(5, 10)
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [131]:
# add a row [51,...,60] to A
A = np.vstack([A, np.arange(51, 61).reshape(1, 10)])
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [132]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1 = A[:3, :]
A2 = A[3:, :]
print(A1)
print(A2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [133]:
# Add 10 to each element of A
A1 = A1 + 10
A2 = A2 + 10
print(A1)
print(A2)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]
[[41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [134]:
# Calculate the square root of each element in A
np.sqrt(A)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781],
       [7.14142843, 7.21110255, 7.28010989, 7.34846923, 7.41619849,
        7.48331477, 7.54983444, 7.61577311, 7.68114575, 7.74596669]])

In [135]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [136]:
# Print the mean, standard devietion of all numbers in M
print('Mean: ', M.mean())
print('Standard deviation: ', M.std())

Mean:  0.058057398079639805
Standard deviation:  0.8833108289226379


In [137]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print('Maximum: ', M.max())
print('3rd quartile: ', np.percentile(M, 75))
print('Median: ', np.median(M))
print('1st quartile: ', np.percentile(M, 25))
print('Minimum: ', M.min())

Maximum:  2.428168500228233
3rd quartile:  0.6164785567348228
Median:  0.09890131541413419
1st quartile:  -0.6123865684927509
Minimum:  -2.302786925285382
